FROM docker.elastic.co/beats/metricbeat:8.10.2

# Copia el archivo de configuración al contenedor
COPY metricbeat.yml /usr/share/metricbeat/metricbeat.yml

# Cambia los permisos del archivo de configuración
RUN chmod go-w /usr/share/metricbeat/metricbeat.yml

# Establece el punto de entrada
ENTRYPOINT ["/usr/share/metricbeat/metricbeat", "-e"]
