version: '3.8'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.10.2
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false  # Desactiva la seguridad
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - elastic
    ulimits:
      memlock:
        soft: -1
        hard: -1
    mem_limit: 2g

  kibana:
    image: docker.elastic.co/kibana/kibana:8.10.2
    container_name: kibana2
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    networks:
      - elastic

  heartbeat:
    image: docker.elastic.co/beats/heartbeat:8.10.2
    container_name: heartbeat2
    user: root
    volumes:
      - ./heartbeat.yml:/usr/share/heartbeat/heartbeat.yml
    networks:
      - elastic
    entrypoint: >
      sh -c "chmod go-w /usr/share/heartbeat/heartbeat.yml &&
             heartbeat -e"

  metricbeat:
    image: docker.elastic.co/beats/metricbeat:8.10.2
    container_name: metricbeat2
    user: root
    volumes:
      - ./metricbeat.yml:/usr/share/metricbeat/metricbeat.yml
    networks:
      - elastic
    entrypoint: >
      sh -c "chmod go-w /usr/share/metricbeat/metricbeat.yml &&
             metricbeat -e"

  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    ports:
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - elastic

  app:
    image: python:3.9-slim
    container_name: ping_app
    command: python /app/server.py
    ports:
      - "8080:8080"
    volumes:
      - ./server.py:/app/server.py
    networks:
      - elastic

networks:
  elastic:
    ipam:
      config:
        - subnet: 172.28.0.0/16
